sonar.projectKey=zhekpyd_Virtual_Stock_Trading_Platform
sonar.sources=cpp_server
sonar.exclusions=cpp_server/vcpkg_installed/**,cpp_server/build/**,cpp_server/build_linux/**,cpp_server/build_jenkins/**
